# Generated by Django 3.1.1 on 2020-09-30 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Airline', '0006_auto_20200929_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='phone',
        ),
    ]
