# Generated by Django 3.1.1 on 2020-09-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Airline', '0007_remove_booking_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='price',
            new_name='Price',
        ),
    ]
